language: javaafter_success:
  - mvn clean test jacoco:report coveralls:report
jdk:
  - oraclejdk8
script: mvn clean install

before_install:
  - npm install -g typescript

after_success:
  - mvn clean test jacoco:report coveralls:report